---
file: log/isucon1/access.log
sort: sum                     # max|min|avg|sum|count|uri|method|max-body|min-body|avg-body|sum-body|p1|p50|p99|stddev
# reverse:                    # boolean
query_string: false
# query_string_ignore_values: # boolean
# decode_uri:                 # boolean
# format:                     # string
# limit:                      # 5000
# noheaders:                  # boolean
# show_footers:               # boolean
matching_groups:
  - "/api/user/[0-9a-zA-Z]+/icon"
  - "/api/user/[0-9a-zA-Z]+/livestream"
  - "/api/livestream/[0-9]+/reaction"
  - "/api/livestream/[0-9]+/livecomment"
  - "/api/livestream/[0-9]+/report"
  - "/api/livestream/[0-9]+/moderate"
  - "/api/livestream/[0-9]+/ngwords"
  - "/api/livestream/[0-9]+/enter"
  - "/api/livestream/[0-9]+/exit"
  - "/api/livestream/[0-9]+"
  - "/api/user/[0-9a-zA-Z]+/statistics"
# filters:                    # string
output: "count,1xx,2xx,3xx,4xx,5xx,method,uri,min,max,sum,avg,p90,p95,p99"
# pos_file:                   # string
# nosave_pos:                 # boolean
# percentiles:                # array
# json:
#   response_time_key: runtime
#   uri_key:           # string
#   method_key:        # string
#   time_key:          # string
#   body_bytes_key:    # string
#   status_key:        # string
