sync_paths:
  isucon1:
  - remote: /etc/systemd/system/isupipe-ruby.service
    local: remote/isupipe-ruby.service
    root: true
  - remote: /etc/nginx/nginx.conf
    local: remote/nginx.conf
    root: true
  - remote: /etc/nginx/sites-enabled/isupipe.conf
    local: remote/nginx-isupipe.conf
    root: true
  - remote: /etc/mysql/mysql.cnf
    local: remote/mysql.cnf
    root: true
  - remote: /home/isucon/env.sh
    local: remote/env-001.sh
  - remote: /home/isucon/webapp/ruby
    local: remote/ruby
  - remote: /home/isucon/webapp/sql
    local: remote/sql
  - remote: /home/isucon/webapp/pdns
    local: remote/pdns
  - remote: /usr/share/pdns-backend-mysql/schema/schema.mysql.sql
    local: remote/pdns-schema.mysql.sql
    root: true
  isucon2:
  - remote: /etc/mysql/mysql.cnf
    local: remote/mysql.cnf
    root: true
  - remote: /etc/mysql/mysql.conf.d/mysqld.cnf
    local: remote/mysqld-002.cnf
    root: true
  - remote: /home/isucon/webapp/sql
    local: remote/sql
  isucon3:
  - remote: /home/isucon/env.sh
    local: remote/env-003.sh
  - remote: /home/isucon/webapp/ruby
    local: remote/ruby
  - remote: /etc/nginx/nginx.conf
    local: remote/nginx.conf
    root: true
  - remote: /etc/nginx/sites-enabled/isupipe.conf
    local: remote/nginx-isupipe-003.conf
    root: true
log_paths:
  isucon1:
  - remote: /var/log/nginx/access.log
    local: log/isucon1/access.log
    root: true
  - remote: /var/log/nginx/error.log
    local: log/isucon1/error.log
    root: true
  isucon2:
  - remote: /var/log/mysql/slow.log
    local: log/isucon1/mysql-slow.log
    root: true
  isucon3:
  - remote: /var/log/nginx/access.log
    local: log/isucon3/access.log
    root: true
  - remote: /var/log/nginx/error.log
    local: log/isucon3/error.log
    root: true
remote_commands:
  setup:
  - cd webapp/ruby
  restart:
  - sudo systemctl daemon-reload
  - sudo systemctl restart isupipe-ruby.service
  - sudo systemctl restart nginx.service
  - sudo systemctl restart mysql.service
ssh:
  user: isucon
  identity_file: ~/.ssh/id_ed25519
servers:
  isucon1: 176.34.59.181
  isucon2: 54.199.132.129
  isucon3: 52.198.24.80
