sync_paths:
  isucon1:
  - remote: /etc/systemd/system/isupipe-ruby.service
    local: remote/isupipe-ruby.service
    root: true
  - remote: /etc/nginx/nginx.conf
    local: remote/nginx.conf
    root: true
  - remote: /etc/nginx/sites-enabled/isupipe.conf
    local: remote/nginx-isupipe.conf
    root: true
  - remote: /etc/mysql/mysql.cnf
    local: remote/mysql.cnf
    root: true
  - remote: /home/isucon/env.sh
    local: remote/env.sh
  - remote: /home/isucon/webapp/ruby
    local: remote/ruby
  - remote: /home/isucon/webapp/sql
    local: remote/sql
  isucon2:
  # - remote: /home/isucon/webapp/ruby
  #   local: remote/ruby
  isucon3:
  # - remote: /home/isucon/webapp/ruby
  #   local: remote/ruby
log_paths:
  isucon1:
  # - remote: /var/log/nginx/access.log
  #   local: log/isucon1/access.log
  #   root: true
  # - remote: /var/log/mysql/slow.log
  #   local: log/isucon1/mysql-slow.log
  #   root: true
remote_commands:
  setup:
  - cd webapp/ruby
  restart:
  # - sudo systemctl daemon-reload
  # - sudo systemctl restart nginx.service
  # - sudo systemctl restart mysql.service
  # - sudo systemctl restart isupipe.service
ssh:
  user: isucon
  identity_file: ~/.ssh/id_ed25519
servers:
  isucon1: 176.34.59.181
  isucon2: 54.199.132.129
  isucon3: 52.198.24.80
